name: "Terraform: 03-services"

on:
  workflow_call:
  pull_request:
    paths:
      - "03-services/**"
      - ".github/workflows/03-services.yaml"
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply (dangerous)"
        required: true
        type: boolean
        default: false

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform Services"
    runs-on: [self-hosted, proxmox, docker]
    environment: Terraform
    defaults:
      run:
        working-directory: ./03-services
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_acme_email: ${{ vars.ACME_EMAIL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out .planfile -input=false
        continue-on-error: true

      - name: Comment Terraform Plan
        if: github.event_name == 'pull_request'
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          planfile: .planfile
          working-directory: ./03-services
          header: "Terraform Plan (03-services)"

      - name: Check Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: |
          (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
          (github.event_name == 'workflow_dispatch' && inputs.apply == true)
        run: terraform apply -auto-approve -input=false
